#!/usr/bin/awk -f

#TODO: recognize headers with dots and extra numbers
# /^\*[0-9]+(\.[0-9]+)?

#TODI: make sure works with extra word headers

/^\*[0-9]+ / {
	if ($0 ~ /^\*[0-9]+ [A-Z]/) {
		if (NR > 1 && !/^\s*$/) {
			print "missing blank line after header at line " NR
		}
	} else {
		print "header not capitalised at line " NR
	}
}


